// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {query} from '../models';

export function GetFields(arg1:string):Promise<Array<main.Field>>;

export function ListStreams():Promise<Array<main.StreamInfo>>;

export function LoadConnection():Promise<main.ConnConfig>;

export function RunQuery(arg1:query.SearchParams):Promise<query.SearchResult>;

export function SaveConnection(arg1:main.ConnConfig):Promise<void>;

export function TestConnection(arg1:main.ConnConfig):Promise<main.ConnInfo>;
