// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ecosystem} from '../models';
import {config} from '../models';
import {metrics} from '../models';
import {query} from '../models';

export function BrowserSignIn(arg1:string,arg2:string):Promise<main.SessionResult>;

export function EcosystemStatus():Promise<ecosystem.EcoStatus>;

export function GetFields(arg1:string):Promise<Array<main.Field>>;

export function GetPrefs():Promise<config.Prefs>;

export function InstallCLI():Promise<void>;

export function InstallSkill():Promise<void>;

export function ListContexts():Promise<Array<main.ContextInfo>>;

export function ListStreams():Promise<Array<main.StreamInfo>>;

export function RemoveContext(arg1:string):Promise<void>;

export function RunMetricsQuery(arg1:metrics.Params):Promise<metrics.Result>;

export function RunQuery(arg1:query.SearchParams):Promise<query.SearchResult>;

export function SaveContext(arg1:main.ConnConfig):Promise<void>;

export function SavePrefs(arg1:config.Prefs):Promise<void>;

export function SessionStatus(arg1:string):Promise<main.SessionInfo>;

export function SetAppearance(arg1:string):Promise<void>;

export function SetDockTheme(arg1:boolean):Promise<void>;

export function SignOut(arg1:string):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function TestConnection(arg1:main.ConnConfig):Promise<main.ConnInfo>;

export function UninstallCLI():Promise<void>;

export function UninstallSkill():Promise<void>;

export function UpgradeCLI():Promise<void>;
