// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserSignIn(arg1, arg2) {
  return window['go']['main']['App']['BrowserSignIn'](arg1, arg2);
}

export function GetFields(arg1) {
  return window['go']['main']['App']['GetFields'](arg1);
}

export function GetPrefs() {
  return window['go']['main']['App']['GetPrefs']();
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListStreams() {
  return window['go']['main']['App']['ListStreams']();
}

export function RemoveContext(arg1) {
  return window['go']['main']['App']['RemoveContext'](arg1);
}

export function RunMetricsQuery(arg1) {
  return window['go']['main']['App']['RunMetricsQuery'](arg1);
}

export function RunQuery(arg1) {
  return window['go']['main']['App']['RunQuery'](arg1);
}

export function SaveContext(arg1) {
  return window['go']['main']['App']['SaveContext'](arg1);
}

export function SavePrefs(arg1) {
  return window['go']['main']['App']['SavePrefs'](arg1);
}

export function SessionStatus(arg1) {
  return window['go']['main']['App']['SessionStatus'](arg1);
}

export function SetAppearance(arg1) {
  return window['go']['main']['App']['SetAppearance'](arg1);
}

export function SetDockTheme(arg1) {
  return window['go']['main']['App']['SetDockTheme'](arg1);
}

export function SignOut(arg1) {
  return window['go']['main']['App']['SignOut'](arg1);
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
