// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFields(arg1) {
  return window['go']['main']['App']['GetFields'](arg1);
}

export function ListStreams() {
  return window['go']['main']['App']['ListStreams']();
}

export function LoadConnection() {
  return window['go']['main']['App']['LoadConnection']();
}

export function RunQuery(arg1) {
  return window['go']['main']['App']['RunQuery'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
