// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {metrics} from '../models';
import {query} from '../models';

export function GetFields(arg1:string):Promise<Array<main.Field>>;

export function GetPrefs():Promise<config.Prefs>;

export function ListContexts():Promise<Array<main.ContextInfo>>;

export function ListStreams():Promise<Array<main.StreamInfo>>;

export function RemoveContext(arg1:string):Promise<void>;

export function RunMetricsQuery(arg1:metrics.Params):Promise<metrics.Result>;

export function RunQuery(arg1:query.SearchParams):Promise<query.SearchResult>;

export function SaveContext(arg1:main.ConnConfig):Promise<void>;

export function SavePrefs(arg1:config.Prefs):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function TestConnection(arg1:main.ConnConfig):Promise<main.ConnInfo>;
