/* A small Markdown parser for GitHub release notes. Pure — no React, no Wails.
 *
 * Deliberately narrow, and deliberately not `marked` + `dompurify`. The bodies it
 * parses are machine-generated by `gh release create --generate-notes` and use a
 * tiny grammar: an `## What's Changed` heading, `* <msg> by @user in <url>`
 * bullets, and a `**Full Changelog**: <url>` line. Two reasons to hand-roll:
 *
 *   1. A general engine hands you an HTML string, which means rendering it with
 *      dangerouslySetInnerHTML. In a Wails app that is worse than the usual XSS
 *      concern: the app IS the WebView, so a real <a href> that the user clicks
 *      navigates the whole window away to GitHub, with no way back. Every link
 *      has to be intercepted and routed through BrowserOpenURL regardless — which
 *      is most of the work this parser does anyway. Emitting a typed tree instead
 *      of HTML makes that structural rather than a thing to remember.
 *   2. It matches the codebase: pure logic in lib/, unit-tested, no runtime deps.
 *
 * The cost: a hand-written release body using tables, images, nested lists or
 * fenced code blocks degrades to plain text. That is acceptable — every surface
 * that renders these notes also links out to the full release page on GitHub.
 */

export type Inline =
  | { t: 'text'; v: string }
  | { t: 'code'; v: string }
  | { t: 'strong'; v: string }
  | { t: 'em'; v: string }
  | { t: 'link'; v: string; href: string };

export type Block =
  | { t: 'h'; level: 2 | 3; c: Inline[] }
  | { t: 'p'; c: Inline[] }
  | { t: 'ul'; items: Inline[][] };

/* Only http(s) URLs ever become links. A `[click](javascript:alert(1))` degrades
 * to plain text, so the renderer can never hand a hostile scheme to
 * BrowserOpenURL. */
function safeHref(url: string): string | null {
  return /^https?:\/\/\S+$/i.test(url) ? url : null;
}

/* Trailing punctuation is almost never part of an autolinked URL — GitHub writes
 * "…in https://github.com/o/r/pull/12." and the period is the sentence's. */
function trimUrlTail(url: string): [string, string] {
  const m = /[.,;:!?)\]]+$/.exec(url);
  if (!m) return [url, ''];
  return [url.slice(0, m.index), url.slice(m.index)];
}

function pushText(out: Inline[], v: string): void {
  if (!v) return;
  const last = out[out.length - 1];
  if (last && last.t === 'text') last.v += v;
  else out.push({ t: 'text', v });
}

/* Inline patterns, tried in order at each position. Code spans come first so that
 * `**` inside backticks stays literal. */
const INLINE = [
  /* `code` */
  { re: /^`([^`]+)`/, make: (m: RegExpExecArray): Inline => ({ t: 'code', v: m[1] }) },
  /* [text](url) */
  {
    re: /^\[([^\]]*)\]\(([^)\s]+)\)/,
    make: (m: RegExpExecArray): Inline | null => {
      const href = safeHref(m[2]);
      return href ? { t: 'link', v: m[1] || m[2], href } : null;
    },
  },
  /* **bold** */
  { re: /^\*\*([^*]+)\*\*/, make: (m: RegExpExecArray): Inline => ({ t: 'strong', v: m[1] }) },
  /* __bold__ */
  { re: /^__([^_]+)__/, make: (m: RegExpExecArray): Inline => ({ t: 'strong', v: m[1] }) },
  /* *em* / _em_ */
  { re: /^\*([^*\s][^*]*)\*/, make: (m: RegExpExecArray): Inline => ({ t: 'em', v: m[1] }) },
  { re: /^_([^_\s][^_]*)_/, make: (m: RegExpExecArray): Inline => ({ t: 'em', v: m[1] }) },
] as const;

/* @mention → a link to the GitHub profile. */
const MENTION = /^@([A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?)/;
const AUTOLINK = /^https?:\/\/[^\s<>]+/i;

export function parseInline(src: string): Inline[] {
  const out: Inline[] = [];
  let i = 0;

  while (i < src.length) {
    const rest = src.slice(i);
    let matched = false;

    for (const { re, make } of INLINE) {
      const m = re.exec(rest);
      if (!m) continue;
      const node = make(m as RegExpExecArray);
      if (node) out.push(node);
      else pushText(out, m[0]); // an unsafe link renders as its literal text
      i += m[0].length;
      matched = true;
      break;
    }
    if (matched) continue;

    const auto = AUTOLINK.exec(rest);
    if (auto) {
      const [url, tail] = trimUrlTail(auto[0]);
      const href = safeHref(url);
      if (href) out.push({ t: 'link', v: url, href });
      else pushText(out, url);
      pushText(out, tail);
      i += auto[0].length;
      continue;
    }

    /* Only at a word boundary: the "@" in an email or a handle already inside a
     * word (a@b) is not a mention. */
    const atBoundary = i === 0 || !/[A-Za-z0-9]/.test(src[i - 1]);
    const mention = atBoundary ? MENTION.exec(rest) : null;
    if (mention) {
      out.push({ t: 'link', v: mention[0], href: `https://github.com/${mention[1]}` });
      i += mention[0].length;
      continue;
    }

    pushText(out, src[i]);
    i += 1;
  }
  return out;
}

const HEADING = /^(#{1,6})\s+(.*)$/;
const BULLET = /^\s*[*-]\s+(.*)$/;

export function parseReleaseNotes(md: string): Block[] {
  const blocks: Block[] = [];
  const lines = (md ?? '').replace(/\r\n?/g, '\n').split('\n');

  let para: string[] = [];
  let bullets: Inline[][] | null = null;

  const flushPara = () => {
    if (!para.length) return;
    /* A single newline inside a paragraph is a soft break: join with a space. */
    const text = para.join(' ').trim();
    para = [];
    if (text) blocks.push({ t: 'p', c: parseInline(text) });
  };
  const flushList = () => {
    if (bullets && bullets.length) blocks.push({ t: 'ul', items: bullets });
    bullets = null;
  };

  for (const line of lines) {
    if (!line.trim()) {
      flushPara();
      flushList();
      continue;
    }

    const h = HEADING.exec(line);
    if (h) {
      flushPara();
      flushList();
      /* Everything above h3 collapses to h3: a release body is a fragment inside
       * our own sheet, not a document with its own title. */
      blocks.push({ t: 'h', level: h[1].length <= 2 ? 2 : 3, c: parseInline(h[2].trim()) });
      continue;
    }

    const b = BULLET.exec(line);
    if (b) {
      flushPara();
      if (!bullets) bullets = [];
      bullets.push(parseInline(b[1].trim()));
      continue;
    }

    flushList();
    para.push(line.trim());
  }
  flushPara();
  flushList();

  return blocks;
}
